import './js/loader.js';
import './js/api-get.js';
import './js/all_categories.js';
import './js/book-card.js';
import './js/header.js';
import './js/pop-up.js';
import './js/support_Ukraine.js';
import './js/theme-switcher.js';
import './js/scroll-up.js';
import './js/user-bar.js'
import './js/autorization.js';
import './js/firebase/firebase-config.js'
import './js/firebase/firebase-autorization.js'
